# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- phase2/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  setupprojectdir: 'SafeguardDevOpsServiceWix'
  setupproject: '**/$(setupprojectdir)/*.wixproj'
  versioningprojectdir: 'ConstructVersionNumber'
  versioningproject: '**/$(versioningprojectdir)/*.csproj'
  pluginsdir: 'ExternalPlugins'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  system.debug: true

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(versioningproject)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: '$(versioningprojectdir)\bin\$(buildConfiguration)\ConstructVersionNumber.exe $(Build.SourcesDirectory)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:buildId=$(Build.BuildId)'

- task: VSBuild@1
  inputs:
    solution: '$(setupproject)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)\$(setupprojectdir)'
    contents: '**\bin\**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)\$(pluginsdir)\bin\$(buildConfiguration)'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)\bin\$(buildConfiguration)\$(pluginsdir)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'SafeguardDevOpsService' 

